openapi: 3.0.1
info:
  title: NTID Writing Style
  description: |
    This describes the API of the NTID Writing Style system.
  # termsOfService: http://swagger.io/terms/
  # contact:
  #   email: apiteam@swagger.io
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
# externalDocs:
#   description: Find out more about Swagger
#   url: http://swagger.io
# servers:
# - url: https://petstore.swagger.io/v2
# - url: http://petstore.swagger.io/v2
tags:
- name: analyze
  description: Analysis of writing samples
  # externalDocs:
    # description: Find out more
    # url: http://swagger.io
paths:
  /analyze:
    post:
      tags:
      - analyze
      summary: Analyze a writing sample
      operationId: updatePet
      requestBody:
        description: Writing sample to be analyzed
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WritingSample'
            example:
              text: Rob is eating lunch.  He is eating a sandwich.
              paragraphs:
                - Rob is eating lunch.  He is eating a sandwich.
              user_id: xyz1234@g.rit.edu
        required: true
        
      responses:
        200:
          description: |
            Results object with an array of recommendations found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
              example:
                recommendation_type: SimpleToCompound
                original_text: Rob is eating lunch.  He is eating a sandwich.
                start_offset: 0
                end_offset: 46
                paragraph_index: 0
                new_values:
                  - Rob is eating lunch, for he is eating a sandwich.
                  - Rob is eating lunch, and he is eating a sandwich.
                  - Rob is eating lunch, but he is eating a sandwich.
                  - Rob is eating lunch, or he is eating a sandwich.
                  - Rob is eating lunch, yet he is eating a sandwich.
                  - Rob is eating lunch, so he is eating a sandwich.
                confidence: 0.6261386275291443
        # 400:
        #   description: Invalid ID supplied
        #   content: {}
        # 404:
        #   description: Pet not found
        #   content: {}
        # 405:
        #   description: Validation exception
        #   content: {}
components:
  schemas:
    WritingSample:
      type: object
      properties:
        text:
          type: string
        paragraphs:
          type: array
          items:
            type: string
        user_id:
          type: string
    ApiResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/Result'
    Result:
      type: object
      properties:
        recommendation_type:
          type: string
          enum:
            - SimpleToCompound
            - ...
        original_text:
          type: string
        start_offset:
          type: integer
        end_offset:
          type: integer
        paragraph_index:
          type: integer
        new_values:
          type: array
          items:
            type: string
        confidence:
          type: number
        
  # securitySchemes:
  #   petstore_auth:
  #     type: oauth2
  #     flows:
  #       implicit:
  #         authorizationUrl: http://petstore.swagger.io/oauth/dialog
  #         scopes:
  #           write:pets: modify pets in your account
  #           read:pets: read your pets
  #   api_key:
  #     type: apiKey
  #     name: api_key
  #     in: header
