version: '3.1'
services:
  web:
    image: registry.gitlab.com/seniorprojectntid/seniorproject:develop
    volumes:
      - type: bind
        source: ./logs
        target: /seniorproject/logs
    environment:
      GRAMMAR_API_URL: http://localhost:8081/v2/check
  grammar:
    image: registry.gitlab.com/seniorprojectntid/seniorproject/grammar:develop
    ports:
      - "8081:8081"
