version: '3.1'
services:
  web:
    image: registry.gitlab.com/seniorprojectntid/seniorproject:develop
  grammar:
    image: registry.gitlab.com/seniorprojectntid/seniorproject-grammar:develop
    ports:
      - "8081:8081"