version: '3.1'
services:
  web:
    image: registry.gitlab.com/seniorprojectntid/seniorproject:develop
    secrets:
      - sentry
  grammar:
    image: registry.gitlab.com/seniorprojectntid/seniorproject-grammar:develop

secrets:
  sentry:
    file: ./.sentry_dsn
